# Generated by Django 6.0.7 on 2026-08-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='primary_supplier',
        ),
    ]
